# Site settings
title: "Riley Wood"
email: rjw245@gmail.com
description: >
    Riley's blog about projects and things.
baseurl: ""
url: "http://rileywood.me/"
title_description: "Riley's blog. Long form description goes here."
title_image: "img/me.png"

# Social usernames/URLs
github_username: rjw245
linkedin_link: https://www.linkedin.com/in/rileywood


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
